name: gas_by_gas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 # State management
  http: ^1.2.2 # API calls
  flutter_local_notifications: ^12.0.0 # Notifications
  geolocator: ^10.0.0 # Geolocation
  google_maps_flutter: ^2.2.0 # For outlet map view
  shared_preferences: ^2.0.15 # Local storage
  intl: ^0.18.0 # Date and time formatting
  firebase_messaging: ^14.0.0 # Push notifications

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
